name: Visceral build

on:
  push:
    branches:
    - main

# We only care about the latest revision of a PR, so cancel previous instances.
concurrency:
  group: msvc-build-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build_visceral:
    name: Build
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3

    - name: Build
      run: |
        msbuild -m -p:Configuration=Release -p:Platform=x86 Gibbed.Visceral.sln

    - name: Finalise?
      run: ls
